spring:
  # runtime environment
  profiles:
    active: dev
  resources:
    static-locations:
      - classpath:/static/
  servlet:
    multipart:
      enabled: true # file upload permit
      max-file-size: 10MB # max of single file size 10M
  # json serialization
  jackson:
    time-zone: GMT+8
    #    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  freemarker:
    request-context-attribute: rc

# forbid default error page
server:
  error:
    whitelabel:
      enabled: false

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

management:
  health:
    db:
      enabled: false
